### ISSUE TITLE
Disable HTTP TRACE method

### ISSUE THREAD

**Issue by MatthewHerbst** [jdeathe/centos-ssh-apache-php#109]
Attack vector: https://www.owasp.org/index.php/Cross_Site_Tracing

Solution: 
```
TraceEnable off
```

This can be set either in the Apache global config or in the vhost config. This will cause Apache to issue a 403 Forbidden in response to TRACE requests.

To test, see the below:

Trace **enabled**:
```
telnet 192.168.99.100 8080
TRACE / HTTP/1.0

HTTP/1.1 200 OK
Date: Wed, 17 Feb 2016 19:20:59 GMT
Server: Apache
Connection: close
Content-Type: message/http
```

Trace **disabled**:
```
telnet 192.168.99.100 8080
TRACE / HTTP/1.0

HTTP/1.1 403 Forbidden
Date: Wed, 17 Feb 2016 19:23:48 GMT
...
```

If you're alright with the issue I'm happy to make a pr for it.

**Comment by jdeathe** [comment]
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=463940

**Comment by MatthewHerbst** [comment]
@jdeathe I won't re-open, but from further looking into this (just Googling around about if/why it should be turned off) it seems almost anyone recommending security settings includes turning this off. Further, multiple vulnerability scanners will show this as a low-level concern.

https://access.redhat.com/solutions/198813

While `TRACE` itself is not a vulnerability, it potentially makes it easier for attackers. I would argue it should be turned off for the same reason you turn off exposing the Apache and/or PHP information.

**Comment by jdeathe** [comment]
Thanks @MatthewHerbst 

I will consider this some more; my initial feeling was that it should be a setting in the VirtualHost configuration rather than in the main Apache config.

**Comment by MatthewHerbst** [comment]
I should also note that as of my recent testing, Apache is now throwing a 405 Method Not Allowed rather than the 403 Forbidden I mentioned in my original comment.

**Comment by jdeathe** [comment]
@MatthewHerbst 

Yes 405 is the expected error code. When installed behind Cloudflare CDN the TRACE method is disabled by default with a 405 error as follows:

```
$ curl -X TRACE https://app-1.deathe.org/
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>
```
