### ISSUE TITLE
how to change defaut app?

### ISSUE THREAD

**Issue by jhzao82** [jdeathe/centos-ssh-apache-php#568]
I want use it for my website, I try to config document root, but It not work.

**Comment by jdeathe** [comment]
I'm not too sure what your asking but there's an example of how to create your own Dockerfile in the php-hello-world repository which shows how to define an alternative DocumentRoot path using `APACHE_CONTENT_ROOT` and `APACHE_PUBLIC_DIRECTORY `: 

- https://github.com/jdeathe/php-hello-world/blob/develop/Dockerfile#L11-L12

**Comment by jhzao82** [comment]
I read the doc before, I try to config APACHE_CONTENT_ROOT and APACHE_PUBLIC_DIRECTORY, to my website path, It's not work fine. I not very know about docker, But I find you project interest to me now.

**Comment by jdeathe** [comment]
Thanks for your interest @jhzao82,

I recommend you have a look at, (maybe even fork), [php-hello-world](https://github.com/jdeathe/php-hello-world) which is the app installed into the image by default. It demonstrates how to use the this image as the source image to build your own app/website image. The source for your app/website needs to be installed into `PACKAGE_PATH ` and that get's linked up to the DocumentRoot path on first run.

If your application is more complex you will likely need to install additional php packages too.

**Comment by jhzao82** [comment]
Thank you! Maybe I want some time to consume, How about install mysql? I know about apt-get install, You also have docker mysql, this project and that project are separate? It seen hard to both run them.

**Comment by jdeathe** [comment]
@jhzao82 You would use a separate MySQL container and connect using a internal docker network. You would need to install the MySQL client `mysql` and the PHP package `php72u-mysqlnd` (and maybe `php72u-pdo`).  The package manager is `yum` as this image is based on CentOS not Debian.

**Comment by jhzao82** [comment]
Thank you. It's a greate job!
