### ISSUE TITLE
Hello, Question About performance

### ISSUE THREAD

**Issue by jhzao82** [jdeathe/centos-ssh-apache-php#569]
I use this pack for my website for a long time, but recently, I found the performance is not high, 

This is ab test result:

ab -n 100 -c 10 http://localhost/

Requests per second:    15.57 [#/sec] (mean)
Time per request:       642.206 [ms] (mean)

Sould I use nginx?

**Comment by jdeathe** [comment]
@jhzao82 

"recently, I found the performance is not high" - You should identify the root cause of the issue that is causing your performance issues.

Did you set `APACHE_MPM=event` as recommended, if so, ngnix will make no difference?

**Comment by jhzao82** [comment]
My site is build by Wordpress , It take too much memroy use, I think That is the problom!

**Comment by jhzao82** [comment]
Maybe I have to check that Is there a  performance issues. Thank you!

**Comment by jdeathe** [comment]
@jhzao82 If you are unable to improve the application's  performance then I should have also mentioned you could consider adding Varnish Cache + HAProxy in front of your web server. HAProxy provides the SSL offloading and Varnish is a full page cache so takes load off the backend servers. You would need to spend some time setting up the configuration of Varnish Cache to work best with your backend application.
- https://github.com/jdeathe/centos-ssh-varnish
- https://github.com/jdeathe/centos-ssh-haproxy
